### ISSUE TITLE
any interest in moving this to Fortran F/OSS Programmers?

### ISSUE THREAD

**Issue by zbeekman** [szaghi/zen-of-fortran#1]
This is really really really an important document. I completely agree, and think that this would benefit from getting in front of as many eyes as possible. It's completely your decision, but if you wanted to make this document slightly more collaborative by hosting the repo on @Fortran-FOSS-programmers I would certainly be thrilled.

**Comment by szaghi** [comment]
Hi @zbeekman .

I know _we agree on many things_, but coding styles is really personal: I was worried to _hurt_ the sensibility of the members in the case to start this document into our group. This is the reason why I start this document on my shoulders. Moreover, I feel that I am too much influenced by Python (the _darkness_ is calling me...).

I have to a _counter-proposal_: we can start a new document of the group , maybe cloning my current document, but clearly invoking the help/contribution of all members. I do not like that other members could think that I am trying to convince them on my _best practices_. On the contrary, I am very very interested to learn your best practices. So my proposal is not to clone/fork/move my guidelines, but create a new ones on the behalf of the group. What do you think?

**Comment by zbeekman** [comment]
I agree, I don't want to impose styles on anyone. But I also agree that the zen of python is brilliant. I would say, don't worry about creating one for the group, unless of course you run out of things to do and find a lot of time on your hands. We've got a lot of projects going and starting a new one which solicits a lot of people for their opinions and input could be a bit overwhelming. I think you are right, and for now, this should be a private repo. I may fork it and tweak some things, I can submit some PRs that you can feel free to accept or decline. Right now I have a lot on my plate, and I know you do too, so I think it's best to wait to create such a document for the group.

**Comment by zbeekman** [comment]
I just saw your gitter.im post... let's see how much interest there is. Feel free to ignore my comments above, let's see what people have to say.

**Comment by szaghi** [comment]
:+1:
